apiVersion: v1
kind: Service
metadata:
    name: blog-front
spec:
    type: NodePort
    selector:
        app: blog-front
        tier: front
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: blog-front
spec:
    selector:
        matchLabels:
            app: blog-front
            tier: front
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 2
    template:
        metadata:
            labels:
                app: blog-front
                tier: front
        spec:
            containers:
                - name: blog-front
                  image: puppyloper/blog-front:1.0.0
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                        name: http
                      - containerPort: 443
                        name: https
