version: "3.2"
services:
    front-app:
        build: ./client
        volumes:
            - "./client:/app"
            - /app/node_modules/
            - /app/public
        networks:
            - frontend
        depends_on:
            - api-server
        ports:
            - "3000:80"

    api-server:
        build: "./server"
        volumes:
            - ./server/src:/go/src
        depends_on:
            - dgraph-server
        networks:
            - frontend
            - backend
            - database
        ports:
            - "10000:80"
        restart: always

    dgraph-zero:
        image: dgraph/dgraph:latest
        volumes:
            - dgraph:/dgraph
        ports:
            - 5080:5080 # For grpc
            - 6080:6080 # For http
        restart: on-failure
        networks:
            - database
        command: dgraph zero --my=dgraph-zero:5080
        # https://github.com/dgraph-io/dgraph/blob/master/dgraph/cmd/zero/run.go

    dgraph-server:
        image: dgraph/dgraph:latest
        volumes:
            - dgraph:/dgraph
        ports:
            - 8080:8080 # For http
            - 9080:9080 # For grpc
        restart: on-failure
        networks:
            - database
            - backend
        command: dgraph server --my=dgraph-server:7080 --lru_mb=2048 --zero=dgraph-zero:5080
        # https://github.com/dgraph-io/dgraph/blob/master/dgraph/cmd/server/run.go#L59-L124

    dgraph-ratel:
        image: dgraph/dgraph:latest
        volumes:
            - dgraph:/dgraph
        ports:
            - 8000:8000
        networks:
            - database
        command: dgraph-ratel
    
networks:
    frontend:
    backend:
    database:

volumes:
    dgraph: