version: "3"
services:
    front-app:
        build: ./client
        volumes:
            - "./client/src:/app/src"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    cpus: '0.2'
                    memory: 256M
        networks:
            - frontend
        depends_on:
            - api-server
        ports:
            - "3000:3000"

    api-server:
        build: "./server"
        volumes:
            - "./server/src/github.com/shharn/blog:/go/src/github.com/shharn/blog"
        depends_on:
            - redis
            # - db
        networks:
            - frontend
            - backend
        deploy:
            replicas: 1
        ports:
            - "10000:10000"
        restart: always

    redis:
        image: redis
        networks:
            - backend
        deploy:
          resources:
              limits:
                  cpus: '0.1'
                  memory: 128M
        ports:
            - "6379:6379"

    # db-zero:
    #     image: dgraph/dgraph:1.0.3
    #     networks:
    #         - backend
    #     deploy:
    #         resource:
    #             imits:
    #                 cpus: '0.5'
    #                 memory: 2048M
    #     ports:
    #         - 
networks:
    frontend:
    backend: