apiVersion: v1
kind: Service
metadata:
    name: front-server-service
spec:
    type: NodePort
    selector:
        app: blog-front
        tier: front
    ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: blog-front
spec:
    selector:
        matchLabels:
            app: blog-front
            tier: front
    replicas: 1
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: blog-front
                tier: front
        spec:
            containers:
                - name: blog-front
                  image: us.gcr.io/${PROJECT_ID}/blog-front-server:test
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3000
                        name: http
---
apiVersion: v1
kind: Service
metadata:
    name: dgraph-server-service
    labels:
        db: dgraph
spec:
    selector:
        db: dgraph
    ports:
    - protocol: TCP
      name: dgraph-server-port
      port: 9080
      targetPort: 9080
---
apiVersion: v1
kind: Service
metadata:
    name: api-server-service
spec:
    type: NodePort
    selector:
        app: api-server
        tier: backend
    ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-server
spec:
    selector:
        matchLabels:
            app: api-server
            tier: backend
    strategy: 
        type: RollingUpdate
    replicas: 1
    template:
        metadata:
            labels:
                app: api-server
                tier: backend
        spec:
            containers:
                - name: blog-api-server
                  image: us.gcr.io/${PROJECT_ID}/blog-api-server:test
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 5000
                        name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: blog-ingress
spec:
    rules:
    - host: blog.puppyloper.com
      http:
          paths:
          - path: /
            backend:
                serviceName: front-server-service
                servicePort: 3000
    - host: api.puppyloper.com
      http:
          paths:
          - path: /
            backend:
                serviceName: api-server-service
                servicePort: 5000
