export const auth = {
    INITIALISE_LOGIN_STATUS: 'INITIALISE_LOGIN_STATUS',
    REQUEST_LOGIN: 'REQUEST_LOGIN',
    LOGIN_PENDING: 'LOGIN_PENDING',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    REQUEST_LOGOUT: 'REQUEST_LOGOUT',
    LOGOUT_WAIT: 'LOGOUT_WAIT',
    LOGOUT_FAILED: 'LOGOUT_FAILED',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    VALIDATE_TOKEN: 'VALIDATE_TOKEN',
    VALID_TOKEN: 'VALID_TOKEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    CLIENT_HAS_NO_TOKEN: 'CLIENT_HAS_NO_TOKEN'
}

export const data = {
    REQUEST_DATA: 'REQUEST_DATA',
    RESPONSE_WAIT: 'RESPONSE_WAIT',
    RESPONSE_ERROR: 'RESPONSE_ERROR',
    RESPONSE_SUCCESS: 'RESPONSE_SUCCESS'
}