version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:8.11.3
          #- image: circleci/golang:1.11.1-alpine3.8
        working_directory: ~/repo/client
        steps:
          - checkout
          - restore_cache:
              keys:
                  - v1-dependencies-{{ checksum "package.json" }}
                  - v1-dependencies-
          - run: yarn install
          - save_cache:
              paths:
                  - node_modules
              key: v1-dependencies-{{ checksum "package.json" }}
    test:
        docker:
            - image: circleci/node:8.11.3
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run: yarn test
            - store_test_results: 
                path: `/test_results
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test