version: 2.1
jobs:
    build-front:
        docker:
            - image: circleci/node:8.11.3
        working_directory: ~/repo
        steps:
          - checkout
          - restore_cache:
              keys:
                  - node-modules-{{ checksum "client/package.json" }}
                  - node-modules-
          - run: 
              working_directory: ~/repo/client
              command: yarn install
          - save_cache:
              paths:
                  - client/node_modules
              key: node-modules-{{ checksum "client/package.json" }}
    test-front:
        docker:
            - image: circleci/node:8.11.3
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - node-modules-{{ checksum "client/package.json" }}
                    - node-modules-
            - run: 
                  working_directory: ~/repo/client
                  command: |
                      mkdir -p ~/test_results/jest
                      yarn test:ci
                      mv jest_result.json ~/test_results/jest/jest_result.json
            - store_test_results: 
                path: ~/test_results
workflows:
    version: 2
    build_and_test:
        jobs:
            - build-front
            - test-front:
                requires:
                    - build-front