version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:8.11.3
        working_directory: ~/repo
        steps:
          - checkout
          - restore_cache:
              keys:
                  - v1-dependencies-{{ checksum "client/package.json" }}
                  - v1-dependencies-
          - run: 
              working_directory: ~/repo/client
              command: yarn install
          - save_cache:
              paths:
                  - node_modules
              key: v1-dependencies-{{ checksum "client/package.json" }}
    test:
        docker:
            - image: circleci/node:8.11.3
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "client/package.json" }}
                    - v1-dependencies-
            - run: 
                  working_directory: ~/repo/client
                  command: yarn test
            - store_test_results: 
                path: /test_results
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test