version: 2
jobs:
    build_and_test:
        docker:
            - image: circleci/node:8.11.3-alpine
          #- image: circleci/golang:1.11.1-alpine3.8
        working_directory: ~/repo
        steps:
          - checkout
          - restore_cache:
              keys:
                  - v1-dependencies-{{ checksum "package.json" }}
                  - v1-dependencies-
          - run: yarn install
          - save_cache:
              paths:
                  - node_modules
              key: v1-dependencies-{{ checksum "package.json" }}
          - run:
              name: Run tests
              command: yarn test
          - store_test_results:
              path: test-results
    workflows:
        version: 2
        ultimate_pipeline:
            jobs:
                - build_and_test