FROM golang:1.11.1-alpine3.8 as base
WORKDIR /go
COPY ./src/github.com/shharn/blog /go/src/github.com/shharn/blog
RUN apk update && \
    apk upgrade && \
    apk add git tzdata&& \
    go get -d ./src/github.com/shharn/blog/... && \
    go install github.com/shharn/blog

FROM golang:1.11.1-alpine3.8
ENV LOG_LEVEL=WARN \
    ENVIRONMENT=production \
    TZ=Asia/Seoul
COPY --from=base /go/bin /go/bin
CMD ["blog"]
