apiVersion: v1
kind: Service
metadata:
    name: dgraph-server
    labels:
        db: dgraph
spec:
    ports:
    - protocol: TCP
      port: 9080
      name: dgraph-server-port
      targetPort: 9080
    selector:
        db: dgraph
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: dgraph
spec:
    selector:
        matchLabels:
            db: dgraph
            tier: backend
    serviceName: "dgraph"
    replicas: 1
    template:
        metadata:
            labels:
                db: dgraph
                tier: backend
        spec:
            terminationGracePeriodSeconds: 30
            containers:
            - name: dgraph-zero
              image: dgraph/dgraph:v1.0.9
              args:
                - dgraph
                - zero
                - --my=localhost:5080
              ports:
              - containerPort: 5080
                name: grpc
              - containerPort: 6080
                name: http
              volumeMounts:
              - name: dgraph-pv
                mountPath: /dgraph-data
            - name: dgraph-server
              image: dgraph/dgraph:v1.0.9
              args:
                - dgraph
                - server
                - --my=localhost:7080
                - --lru_mb=2048
                - --zero=localhost:5080
              ports:
              - containerPort: 8080
                name: http
              - containerPort: 9080
                name: grpc
              volumeMounts:
              - name: dgraph-pv
                mountPath: /dgraph-data
    volumeClaimTemplates:
    - metadata:
          name: dgraph-pv
      spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
                storage: 5Gi