apiVersion: v1
kind: Service
metadata:
    name: blog-api-server
spec:
    type: NodePort
    selector:
        app: api-server
        tier: backend
    ports:
    - protocol: TCP
      name: http
      port: 80
    - protocol: TCP
      name: https
      port: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-server
spec:
    selector:
        matchLabels:
            app: api-server
            tier: backend
    strategy: 
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 2
    replicas: 1
    template:
        metadata:
            labels:
                app: api-server
                tier: backend
        spec:
            containers:
                - name: blog-api-server
                  image: puppyloper/blog-api-server:1.0.0
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                        name: http
                      - containerPort: 443
                        name: https
